site_name: Mouse Genetics
pages:
 - Home: index.md
 - Connect to Galaxy server: about.md
 - BWA mem tool: getting_started.md
 - customizations.md
 - Installing tools and workflows: installing_tools_and_workflows.md
 - Examples:
   - examples/docker.md
   - examples/vagrant.md
 - Frequently asked questions: faq.md
 - Available roles: available_roles.md
 - Available variables: available_variables.md
 - GalaxyKickStart Use Cases: 
   - metavisitor.md
   - GKS2slurm.md
   - GKSfromWorflows.md
theme: readthedocs
